"""update device

Revision ID: 36ef0e2124a9
Revises: d679a08d17ee
Create Date: 2024-08-25 15:54:44.613371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ef0e2124a9'
down_revision: Union[str, None] = 'd679a08d17ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('date_turn_on', sa.DateTime(), nullable=True))
    op.add_column('device', sa.Column('date_turn_off', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'date_turn_off')
    op.drop_column('device', 'date_turn_on')
    # ### end Alembic commands ###
