"""update device fild name/type

Revision ID: 8c30e3e815da
Revises: 8cfc9be9fe8f
Create Date: 2024-09-14 19:29:43.825683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c30e3e815da'
down_revision: Union[str, None] = '8cfc9be9fe8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'status')
    op.drop_column('device', 'date_turn_on')
    op.drop_column('device', 'date_turn_off')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('date_turn_off', mysql.DATETIME(), nullable=True))
    op.add_column('device', sa.Column('date_turn_on', mysql.DATETIME(), nullable=True))
    op.add_column('device', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
