"""update device fild name/type

Revision ID: 8cfc9be9fe8f
Revises: 12a96a5d208b
Create Date: 2024-09-01 20:01:27.298898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8cfc9be9fe8f'
down_revision: Union[str, None] = '12a96a5d208b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('ieee', sa.String(length=256), nullable=False))
    op.alter_column('device', 'name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.drop_column('device', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('address', mysql.VARCHAR(length=256), nullable=False))
    op.alter_column('device', 'name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.drop_column('device', 'ieee')
    # ### end Alembic commands ###
