"""init

Revision ID: 8e15af4213e9
Revises: 
Create Date: 2024-07-20 12:59:15.993667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e15af4213e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('type', sa.Enum('ON_OFF_SWITCH', 'LEVEL_CONTROL_SWITCH', 'ON_OFF_OUTPUT', 'LEVEL_CONTROLLABLE_OUTPUT', 'SCENE_SELECTOR', 'CONFIGURATION_TOOL', 'REMOTE_CONTROL', 'COMBINED_INTERFACE', 'RANGE_EXTENDER', 'MAIN_POWER_OUTLET', 'DOOR_LOCK', 'DOOR_LOCK_CONTROLLER', 'SIMPLE_SENSOR', 'CONSUMPTION_AWARENESS_DEVICE', 'HOME_GATEWAY', 'SMART_PLUG', 'WHITE_GOODS', 'METER_INTERFACE', 'ON_OFF_LIGHT', 'DIMMABLE_LIGHT', 'COLOR_DIMMABLE_LIGHT', 'ON_OFF_LIGHT_SWITCH', 'DIMMER_SWITCH', 'COLOR_DIMMER_SWITCH', 'LIGHT_SENSOR', 'OCCUPANCY_SENSOR', 'ON_OFF_BALLAST', 'DIMMABLE_BALLAST', 'ON_OFF_PLUG_IN_UNIT', 'DIMMABLE_PLUG_IN_UNIT', 'COLOR_TEMPERATURE_LIGHT', 'EXTENDED_COLOR_LIGHT', 'LIGHT_LEVEL_SENSOR', 'SHADE', 'SHADE_CONTROLLER', 'WINDOW_COVERING_DEVICE', 'WINDOW_COVERING_CONTROLLER', 'HEATING_COOLING_UNIT', 'THERMOSTAT', 'TEMPERATURE_SENSOR', 'PUMP', 'PUMP_CONTROLLER', 'PRESSURE_SENSOR', 'FLOW_SENSOR', 'MINI_SPLIT_AC', 'IAS_CONTROL', 'IAS_ANCILLARY_CONTROL', 'IAS_ZONE', 'IAS_WARNING_DEVICE', 'COLOR_CONTROLLER', 'COLOR_SCENE_CONTROLLER', 'NON_COLOR_CONTROLLER', 'NON_COLOR_SCENE_CONTROLLER', 'CONTROL_BRIDGE', 'ON_OFF_SENSOR', name='devicetype'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    # ### end Alembic commands ###
