"""update colum, add statistic

Revision ID: d679a08d17ee
Revises: 9fb2e92ba1e7
Create Date: 2024-08-24 21:28:05.202470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd679a08d17ee'
down_revision: Union[str, None] = '9fb2e92ba1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('pause', sa.Boolean(), nullable=False),
    sa.Column('cron_str', sa.String(length=256), nullable=False),
    sa.Column('last_poll', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduler')
    # ### end Alembic commands ###
